### ISSUE TITLE
Error when trying to run BM3DCPU

### ISSUE THREAD

**Issue by brucethemoose** [shssoichiro/soifunc#1]
As the title says ^

`clip = soifunc.BM3DCPU(clip)`

```
Python exception: No attribute with the name bm3dcpu exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
File "src/cython/vapoursynth.pyx", line 2866, in vapoursynth._vpy_evaluate
File "src/cython/vapoursynth.pyx", line 2867, in vapoursynth._vpy_evaluate
File "/home/alpha/Storage/clone/StableDiffusion-Video2Video/SDtest.vpy", line 17, in 
clip = soifunc.denoise.BM3DCPU(clip, profile="fast", sample=1)
File "/usr/lib/python3.10/site-packages/soifunc/denoise.py", line 129, in BM3DCPU
return BM3DFast(input, algorithm="bm3dcpu", **kwargs)
File "/usr/lib/python3.10/site-packages/soifunc/denoise.py", line 207, in BM3DFast
alg_namespace = getattr(core, algorithm)
File "src/cython/vapoursynth.pyx", line 2434, in vapoursynth._CoreProxy.__getattr__
File "src/cython/vapoursynth.pyx", line 2308, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name bm3dcpu exists. Did you mistype a plugin namespace?
```

I thought I was just importing it wrong, but looks like its being thrown from inside BM3DCPU.

**Comment by brucethemoose** [comment]
Oh never mind I didn't realize there was a seperate package for Wolfram's BM3D.

I actually have the CUDA version, but I am testing something thats going to keep my GPU VRAM full.
